services:
  nginx:
    build:
      requirements/nginx
    ports:
    # main
      # - "80:80"
      # - "443:443"
      # - "8080"
    # project_zomboid
      - "16261-16272:16261-16272/udp"
    # satisfactory
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "8888:8888/tcp"
    # enshrouded
      - "15637:15637/udp"
    networks:
      - main_network
    restart:
      always

  project_zomboid:
    build:
      requirements/project_zomboid
    volumes:
      - project_zomboid:/root/Zomboid
    networks:
      - main_network
    env_file:
      - .env
    secrets:
      - project_zomboid_admin_pass
    restart:
      always

  satisfactory:
    build:
      requirements/satisfactory
    volumes:
      - satisfactory_conf:/home/ubuntu/SatisfactoryDedicatedServer/FactoryGame/Saved
      - satisfactory_save:/home/ubuntu/.config/Epic/FactoryGame/Saved
    networks:
      - main_network
    restart:
      always

  enshrouded:
    build:
      requirements/enshrouded
    volumes:
      - enshrouded:/home/ubuntu/EnshroudedDedicatedServer/savegame
    networks:
      - main_network
    restart:
      always

volumes:
  project_zomboid:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ~/data/project_zomboid

  satisfactory_conf:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ~/data/satisfactory/conf

  satisfactory_save:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ~/data/satisfactory/save

  enshrouded:
    driver:
      local
    driver_opts:
      type:
        none
      o:
        bind
      device:
        ~/data/enshrouded

secrets:
  project_zomboid_admin_pass:
    file: secrets/project_zomboid_admin_pass.txt

networks:
  main_network:
    driver:
      bridge
